feat: add feedback button
ocaml-sf/learn-ocaml pull request #535
Opened 2023-04-11 13:42 UTC by Plictox

* **Kind:** enhancement

* Close #525 

### Description

### Checklist

* [x] Read the [CONTRIBUTING.md](https://github.com/ocaml-sf/learn-ocaml/blob/master/CONTRIBUTING.md) guide and:
  * [x] Use [Atomic Commits](https://github.com/ocaml-sf/learn-ocaml/blob/master/CONTRIBUTING.md#atomic-commits) so each commit gathers a single logical change
  * [x] Use [Conventional Commits](https://github.com/ocaml-sf/learn-ocaml/blob/master/CONTRIBUTING.md#conventional-commits) regarding commit messages (needed by our release toolchain)
* [ ] Add/update [tests](https://github.com/ocaml-sf/learn-ocaml/tree/master/tests#readme)
  
* [ ] Add/update [documentation](https://github.com/ocaml-sf/learn-ocaml/tree/master/docs)
  
* [ ] …
  

### Note to maintainers

* Read [this wiki page](https://github.com/ocaml-sf/learn-ocaml/wiki/Checklist-for-testing-and-merging-a-PR).
* Make sure the PR has a **milestone**.
* ***Assign*** yourself before merging.
* Either do a regular **merge**:
  * for PRs containing *several commits* following [conventional-commits](https://github.com/ocaml-sf/learn-ocaml/blob/master/CONTRIBUTING.md#conventional-commits),
  * or for PRs containing 1 commit shared with a later PR (to preserve the SHA1)
* Or do a **squash-merge**:
  * for PRs containing *only 1 commit* (not shared with a later PR),
  * or for PRs containing several commits that need not be kept in the history;
  * → ***Update the commit message header*** with a [conventional-commit type](https://github.com/ocaml-sf/learn-ocaml/blob/master/CONTRIBUTING.md#conventional-commits-examples),
  * → ***Add a footer*** `Close #…` if a related issue exists.

2023-04-11 14:08 UTC, erikmd requested changes
Thanks @Plictox !

I left a few comments for your PR

2023-04-11 14:08 UTC, erikmd commented on static/css/learnocaml_main.css
> +    border-right: 1px #eee solid !important;
Is it really needed?
```suggestion
    border-left: 1px #eee solid !important;
```

2023-04-11 14:08 UTC, erikmd commented on static/index.html
> +        </button>
```suggestion
        <a class="btn" href="https://github.com/learn-ocaml-community/teaching-feedback#readme" target = "_blank">
          <img src="/icons/icon_feedback.svg">
```

(to comply with usual *accessibility rules*: `<a>` is better than `<button>` here, https://a11y-101.com/design/button-vs-link )

**and TODO:** You forgot to commit the .svg image.

2023-04-11 14:19 UTC, erikmd commented
> Suggestion (to tweak further w.r.t. spacing)

actually the spacing looks fine now.

Two leftover tasks:

* Convert draw style from black to white
* Add an id `<img id="learnocaml-main-feedback" src="/icons/icon_feedback.svg">` to make it possible to add an attribute `title="Send Feedback"`, internationalized, thanks to some js_of_ocaml code.

2023-04-18 17:46 UTC, erikmd approved these changes
@Plictox, that looks very good to me, thanks!

Here is the outcome of your PR:

![2023-04-18_19-12-04_Screenshot_a_img](https://user-images.githubusercontent.com/10367254/232860153-38c8e704-05ac-4316-ab8c-4de5ee3d51ff.png)

→ note in passing that your CSS code induced a slight (unwanted) shift of the `Learn OCaml` text. This is only due to the `margin-top:` property, that is unnecessary.

Finally, note that the `margin-left` should rather be put outside the link `<a href=_>` rather than inside, so that the surrounding black space is not clickable.

I'll push a commit and rebase your pull request, so that we can get two final commits to be merged.

Thanks.

2023-04-18 18:17 UTC, erikmd commented
Now, let's wait for the CI :white_check_mark:

2023-04-18 19:14 UTC, merged

2023-04-19 07:34 UTC, Plictox commented
This feature could be improved by implementing a sidebar. It would be more complex but way more elegant ! cf the google feedback option
![image](https://user-images.githubusercontent.com/77079482/233002362-0d524964-72b7-4118-8231-81cd5a231626.png)